-- Big Dawg HQ Schema
-- Run this in Supabase SQL Editor (safe to re-run; uses IF NOT EXISTS).
-- If you already ran the original schema, only the additions at the bottom are new.

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  cat text not null,
  name text not null,
  done boolean not null default false,
  priority text not null default 'medium' check (priority in ('high', 'medium', 'low')),
  due jsonb,
  urgent boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bills (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  amount numeric not null,
  freq text not null check (freq in ('Monthly', 'Weekly')),
  day integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tasks enable row level security;
alter table public.bills enable row level security;

drop policy if exists "Users can read own tasks" on public.tasks;
drop policy if exists "Users can insert own tasks" on public.tasks;
drop policy if exists "Users can update own tasks" on public.tasks;
drop policy if exists "Users can delete own tasks" on public.tasks;

create policy "Users can read own tasks" on public.tasks for select using (auth.uid() = user_id);
create policy "Users can insert own tasks" on public.tasks for insert with check (auth.uid() = user_id);
create policy "Users can update own tasks" on public.tasks for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete own tasks" on public.tasks for delete using (auth.uid() = user_id);

drop policy if exists "Users can read own bills" on public.bills;
drop policy if exists "Users can insert own bills" on public.bills;
drop policy if exists "Users can update own bills" on public.bills;
drop policy if exists "Users can delete own bills" on public.bills;

create policy "Users can read own bills" on public.bills for select using (auth.uid() = user_id);
create policy "Users can insert own bills" on public.bills for insert with check (auth.uid() = user_id);
create policy "Users can update own bills" on public.bills for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete own bills" on public.bills for delete using (auth.uid() = user_id);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_tasks_updated_at on public.tasks;
create trigger set_tasks_updated_at before update on public.tasks for each row execute function public.set_updated_at();

drop trigger if exists set_bills_updated_at on public.bills;
create trigger set_bills_updated_at before update on public.bills for each row execute function public.set_updated_at();

-- ────────── ZAPIER ACCESS VIEW ──────────
-- Optional: lets you query tasks via Zapier using a service role key
-- without exposing the whole DB. Already covered by RLS for direct access.
